version: '3'
services:
  mongo:
    image: mongo
    container_name: post-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  oracle:
    image: oracle/database:19.3.0-ee
    container_name: post-oracle
    ports:
      - "1521:1521"
      - "5500:5500"
    environment:
      ORACLE_SID: ${ORACLE_SID}
      ORACLE_PDB: ${ORACLE_PDB}
      ORACLE_PWD: ${ORACLE_PASSWORD}
    volumes:
      - oracle_data:/opt/oracle/oradata
  
  app:
    build: .
    container_name: post-app
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      - MONGO_URI=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@post-mongo:27017/${MONGO_DB_NAME}?authSource=admin
      - APP_PORT=${APP_PORT}
      - ORACLE_URI=post-oracle:1521/${ORACLE_PDB}
      - ORACLE_USER=${ORACLE_USER}
      - ORACLE_PASSWORD=${ORACLE_PASSWORD}
    depends_on:
      - mongo
      - oracle

volumes:
  mongo_data:
  oracle_data: